const chalk = require('chalk');
const chalkAnimation = require('chalk-animation');
const log = console.log;

log(chalk.magentaBright("Kirby ") + chalk.white("and ") + chalk.magenta("Friends: ") + chalk.white('The Picnic'));
log(chalk.cyanBright("Written by: ") + chalk.cyan("Sammy Stark"));
log(chalk.white("It was a beautiful day at Dream Land."));
log(chalk.white("Oh, who is this walking around?"));
log(chalk.white("It looked like a ") + chalk.magentaBright("pink round puffball ") + chalk.white("with ")  + chalk.magentaBright("pink round hands ")  + chalk.white(", ") + chalk.redBright("red round feet")  + chalk.white(", and ") + chalk.blue("blue-tiful blue eyes") + chalk.white('.'));
log(chalk.white("It looked like it was carrying a basket."))
log(chalk.magentaBright("'Hi there! My name is Kirby!'") + chalk.white(" Kirby said as he introduced himself."));
log(chalk.magentaBright("'Today, I'm going on a picnic with my friends!'") + chalk.white(" Kirby informed."));
log(chalk.white("Where will Kirby and his friends have their picnic today?"));
log(chalk.magentaBright("'We will have our picnic up the hill over there.'") + chalk.white(' Kirby said as he point up toward the hill.'));
log(chalk.magentaBright("'That way, not only we'll enjoy the food, but we can also enjoy the meadow, enviornment atmosphere around us'") + chalk.white(' Kirby added.'));
log(chalk.white("And so, Kirby, with his basket heads straight up to the hill. He sets the picnic blanket up, and when Kirby starts to get the food he brought to the picnic, he smells a beautiful breeze."));
log(chalk.magentaBright("'Ahhh, the scent of the beautiful breeze.'") + chalk.white(' Kirby complimented to the breezing scent in the air.'));
log(chalk.white("Then, Kirby see someone else walking up to the hill."));
log(chalk.white("It looked like Kirby, but it was a " + chalk.yellowBright("yellow round puffball ") + chalk.white("with ")  + chalk.yellowBright("yellow round hands ")  + chalk.white(", ") + chalk.redBright('orange round feet'))  + chalk.white(", ") + chalk.red('brown eyes')  + chalk.white(", and a small eyelash on each eye") + chalk.white('.'));
log(chalk.magentaBright("'Hey, it's one of my best friends Laini! Hi, Laini!' ") + chalk.white('Kirby said excitedly while waving.'));
log(chalk.yellowBright("'Hi, Kirby!' ") + chalk.white('Laini said excitedly as she waves back.'));
log(chalk.white('It appears that Laini brought something with her for the picnic.'));
log(chalk.magentaBright("'Oh, what did you bring for the picnic, Laini?' ") + chalk.white('Kirby asked Laini.'));
log(chalk.yellowBright("'Oh, I brought a bottle of water for each of us.' ") + chalk.white('Laini replied.'));
log(chalk.magentaBright("'Oh, that's very sweet of you, Laini.' ") + chalk.white('Kirby said with a smile.'));
log(chalk.yellowBright("'Well, since it's nice and warm out, I thought I bring some water for us to keep us hydrated.' ") + chalk.white('Laini said with a smile.'));
log(chalk.magentaBright("'Thank you, BFF.' ") + chalk.white('Kirby said as he appreciate the bottles of water.'));
log(chalk.yellowBright("'You're welcome, BFF.' ") + chalk.white('Laini replied.'));
log(chalk.white("Then, there was another round puffball walking up to the hill."));
log(chalk.white("It looked like Kirby and Laini, but it was a " + chalk.cyanBright("cyan round puffball ") + chalk.white("with ")  + chalk.cyanBright("cyan round hands ")  + chalk.white(", ") + chalk.blue('blue round feet'))  + chalk.white(", and ") + chalk.gray('gray eyes') + chalk.white('.'));
log(chalk.yellowBright("'Hey, it's our friend Sky!' ") + chalk.white('Laini said with excitement!'));
log(chalk.magentaBright("'Hi, Sky!' ") + chalk.white('Kirby said excitedly while waving.'));
log(chalk.yellowBright("'Hi, Sky! How are you today?' ") + chalk.white('Laini said excitedly while waving.'));
log(chalk.cyanBright("'Hey, besties! I'm doing great! I am looking forward to our picnic today!'") + chalk.white(' Sky said as he sits with his two besties Kirby and Laini.'));
log(chalk.white("It appears that Sky brought something with him for the picnic."));
log(chalk.yellowBright("'Oh, what did you bring for the picnic, Sky?' ") + chalk.white('Laini asked Sky.'));
log(chalk.cyanBright("'Oh, I brought some chips for each of us.'") + chalk.white(' Sky replied.'));
log(chalk.magentaBright("'I love chips! They are such a great snack!' ") + chalk.white('Kirby added.'));
log(chalk.yellowBright("'And do you know what chips go good with?' ") + chalk.white('Laini asked while in topic.'));
log(chalk.cyanBright("'What's that, Laini?' ") + chalk.white('Sky wondered in curiosity.'));
log(chalk.white("Before Laini could answer Sky's question, there was another round puffball walking up to the hill."));
log(chalk.white("It looked like Kirby, Laini and Sky, but it was a " + chalk.redBright("red round puffball ") + chalk.white("with ")  + chalk.redBright("red round hands ")  + chalk.white(", ") + chalk.red('dark red round feet'))  + chalk.white(", and ") + chalk.magenta('purple eyes') + chalk.white('.'));
log(chalk.magentaBright("'Oh, it's our friend Flame! Hi, Flame!' ") + chalk.white('Kirby said as he waved at Flame with excitement!'));
log(chalk.yellowBright("'Hi there, Flame!' ") + chalk.white('Laini added.'));
log(chalk.cyanBright("'Hey, Flame! How's it going?' ") + chalk.white('Sky added.'));
log(chalk.redBright("'Hi, guys! I'm doing great! I'm so excited for our picnic!' ") + chalk.white('Flame replied as he sat down with his friends.'));
log(chalk.white("It appears that Flame brought something with him for the picnic."));
log(chalk.cyanBright("'Oh, whatcha got with you, Flame?' ") + chalk.white('Sky asked Flame.'));
log(chalk.redBright("'Oh, I made each of us a sandwich for the picnic.'") + chalk.white(' Flame replied, as he handed.'));
log(chalk.magentaBright("'Oh, thank you Flame! They look so heavenly right now!'") + chalk.white(' Kirby said gratefully.'));
log(chalk.yellowBright("'You did such an amazing job making these sandwiches, Flame.'") + chalk.white(' Laini complemented.'));
log(chalk.redBright("'Awww, thank you, Laini.'") + chalk.white(" Flame replied to Laini's complement."));
log(chalk.cyanBright("'I'm so excited to enjoy our picnic!'") + chalk.white(" Sky said as he's ready to dig in with his sandwich."));
log(chalk.yellowBright("'Wait a minute!'") + chalk.white(" Laini then turned to Kirby."));
log(chalk.magentaBright("'What is it, Laini?'") + chalk.white(" Kirby asked Laini out of curiosity."));
log(chalk.yellowBright("'Kirby, we never asked you what you brought for the picnic yet!'") + chalk.white(" Laini said as she realized Kirby didn't get to share what he brought."));
log(chalk.cyanBright("'I almost forgot that Kirby didn't say what he brought yet!'") + chalk.white(" Sky added."));
log(chalk.redBright("'What did you bring for the picnic, Kirby?'") + chalk.white(" Flame asked Kirby."));
log(chalk.magentaBright("'I never thought you guys asked.'") + chalk.white(" Kirby said after he laughed with a smile."));
log(chalk.white("Kirby then brings his basket over, and picks up a box. What could be inside?"));
log(chalk.magentaBright("'Well, since it's no picnic without something sweet...'") + chalk.white(" Kirby said with a smile."));
log(chalk.white("Kirby opened the box, and everyone looked inside. Then, they gasped as their mouths started watering! What could be inside?"));
log(chalk.yellowBright("'It's so sweet!'") + chalk.white(" Laini replied."));
log(chalk.cyanBright("'It's so fluffy!'") + chalk.white(" Sky replied."));
log(chalk.redBright("'It's so heavenly, it's making my mouth water!'") + chalk.white(" Flame replied."));
log(chalk.magentaBright("'It's a sweet, fluffy, mouth-watering Strawberry Shortcake!'") + chalk.white(" Kirby replied to his friends."));
log(chalk.magentaBright("'And, I got a slice for each of us.'") + chalk.white(" Kirby added, as he handed each of his friends a slice."));
log(chalk.yellowBright("'Thank you, Kirby. I think we should save these after we finished our sandwich and chips.'") + chalk.white(" Laini suggested after she was grateful for her slice of cake."));
log(chalk.white("Laini then put her slice of cake right by her."))
log(chalk.cyanBright("'I agree with Laini! Desserts like this should be saved for last because we always save the best for last.'") + chalk.white(" Sky said, as he's ready to dig in with his sandwich!"));
log(chalk.white("Kirby smiled after hearing the last part."));
log(chalk.redBright("'Well, I'm ready for our picnic!'") + chalk.white(" Flame said as he's ready to enjoy his sandwich."));
log(chalk.white("Kirby was excited as well."));
log(chalk.magentaBright("'Then let's dig in, shall we?'") + chalk.white(" Kirby said as he's ready to enjoy the picnic."));
log(chalk.white("Kirby, Laini, Sky, and Flame get ready for their picnic. But before they dig in, they said altogether..."));
chalkAnimation.rainbow("'This is going to be the BEST PICNIC EVER!!!'");